project:
  type: website
  output-dir: docs

website:
  title: "Like a Fish Out of Water"
  description: "Seasonal variation in spawning habitats and spatio-temporal genetic adaptation of a vulnerable species"
  navbar:
    title: "Like a Fish Out of Water"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/john-proefrock/

format:
  html:
    theme: default

execute:
  freeze: auto
